import SwiftUI

extension Font {
    static let displayXL = Font.custom("Fraunces-9ptBlackItalic", size: 96, relativeTo: .largeTitle)
    static let displayL = Font.custom("Fraunces-9ptBlackItalic", size: 64, relativeTo: .title)
    static let displayWins = Font.custom("Fraunces-9ptBlackItalic", size: 104, relativeTo: .largeTitle)
    static let brandTitle = Font.custom("Fraunces-9ptBlackItalic", size: 19, relativeTo: .headline)
    static let cardTitle = Font.custom("Fraunces-9ptBlackItalic", size: 22, relativeTo: .title2)
    static let statFigure = Font.custom("Fraunces-9ptBlackItalic", size: 17, relativeTo: .headline)
    static let tycoonTitle = Font.custom("InstrumentSans-Regular", size: 24, relativeTo: .title3).weight(.semibold)
    static let tycoonBody = Font.custom("InstrumentSans-Regular", size: 16, relativeTo: .body)
    static let tycoonCaption = Font.custom("InstrumentSans-Regular", size: 11, relativeTo: .caption).weight(.medium)
    static let bodyMono = Font.system(size: 13, design: .monospaced)
    static let drawerTitle = Font.custom("Fraunces-9ptBlackItalic", size: 20, relativeTo: .headline)
    static let ruleTitle = Font.custom("InstrumentSans-Regular", size: 12, relativeTo: .caption).weight(.semibold)
    static let ruleCaption = Font.custom("InstrumentSans-Regular", size: 10, relativeTo: .caption2)
    static let settingsRowTitle = Font.custom("InstrumentSans-Regular", size: 15, relativeTo: .body).weight(.semibold)
    static let settingsRowSubtitle = Font.custom("InstrumentSans-Regular", size: 12, relativeTo: .caption)
    static let badgeLabel = Font.custom("Fraunces-9ptBlackItalic", size: 16, relativeTo: .callout)
    static let badgeLabelSmall = Font.custom("Fraunces-9ptBlackItalic", size: 13, relativeTo: .footnote)
    static let profileLevel = Font.custom("Fraunces-9ptBlackItalic", size: 32, relativeTo: .title)
    static let profileStatFigure = Font.custom("Fraunces-9ptBlackItalic", size: 20, relativeTo: .title3)
    static let sectionLabel = Font.custom("InstrumentSans-Regular", size: 8, relativeTo: .caption2).weight(.semibold)
    static let resultHeroRank = Font.custom("Fraunces-9ptBlackItalic", size: 56, relativeTo: .largeTitle)
    static let resultBrandSmall = Font.custom("Fraunces-9ptBlackItalic", size: 14, relativeTo: .footnote)
    static let resultPosition = Font.custom("Fraunces-9ptBlackItalic", size: 18, relativeTo: .callout)
    static let resultButton = Font.custom("InstrumentSans-Regular", size: 13, relativeTo: .callout).weight(.semibold)
    static let resultEyebrow = Font.custom("InstrumentSans-Regular", size: 9, relativeTo: .caption2).weight(.semibold)
    static let resultMeta = Font.custom("InstrumentSans-Regular", size: 10, relativeTo: .caption2).weight(.medium)
    static let resultMetaStrong = Font.custom("InstrumentSans-Regular", size: 10, relativeTo: .caption2).weight(.semibold)
}

#Preview {
    VStack(alignment: .leading, spacing: 20) {
        Text("96")
            .font(.displayXL)
            .foregroundStyle(Color.cardCream)
        Text("Display L")
            .font(.displayL)
            .foregroundStyle(Color.cardLavender)
        Text("Title — Semibold")
            .font(.tycoonTitle)
            .foregroundStyle(Color.textPrimary)
        Text("Body — Regular")
            .font(.tycoonBody)
            .foregroundStyle(Color.textSecondary)
        Text("CAPTION — MEDIUM")
            .font(.tycoonCaption)
            .textCase(.uppercase)
            .foregroundStyle(Color.textTertiary)
        Text("0x1A3F monospaced")
            .font(.bodyMono)
            .foregroundStyle(Color.cardMint)
    }
    .padding(32)
    .frame(maxWidth: .infinity, alignment: .leading)
    .background(Color.tycoonBlack)
}
